# services:
#   mediamtx:
#     image: bluenviron/mediamtx:latest   # Última versión estable (hoy v1.15.0)
#     container_name: mediamtx
#     restart: unless-stopped
#     network_mode: host                  # Recomendado para RTSP/UDP (Linux)
#     volumes:
#       - ./mediamtx.yml:/mediamtx.yml:ro # Opcional: tu config personalizada
#       - ./recordings:/recordings        # Opcional: si activás grabaciones
#     # environment:                      # Ejemplos opcionales:
#     #   - MTX_WEBRTCADDITIONALHOSTS=tudominio.com,IP_PUBLICA
#     #   - MTX_PATHS_cam_entrada_SOURCE=rtsp://cam-ip/stream

services:
  mediamtx:
      image: bluenviron/mediamtx:latest
      container_name: mediamtx
      restart: unless-stopped
      ports:
        - "8554:8554/tcp"   # RTSP
        - "1935:1935/tcp"   # RTMP
        - "8888:8888/tcp"   # HLS
        - "8889:8889/tcp"   # WebRTC HTTP (WHIP/WHEP)
        - "8189:8189/udp"   # WebRTC ICE/UDP
      volumes:
        - ./mediamtx.yml:/mediamtx.yml:ro
        - ./recordings:/recordings